Improve top panel elements
cmu-delphi/www-epivis pull request #54
Opened 2024-08-07 20:20 UTC by rzats

Closes #44 and #46:

- The autofitting feature added in #36 has been turned into a new navigation mode, which is enabled by default.
  - It is mutually exclusive with pan, scroll or crop modes - so once a user looks at a particular area of the chart, enabling or disabling signals will no longer reset their viewport.
  - Adding a new signal will reset the mode to "autofit" again. 
- The "Scale by 1/mean" and "Reset Dataset Scaling" buttons are moved into their own group, and given more appropriate icons. Also, navigation mode icons are now positioned on the top left of the screen.
- The introductory interactive tour has been re-ordered so that top menu items are explained first.

2024-08-14 22:15 UTC, melange396 requested changes
This is awesome, and the new mode works well!  Ive got just a few comments on presentation...

2024-08-14 22:15 UTC, melange396 commented on src/components/TopMenu.svelte
> +      uk-tooltip><Fa icon={faMinimize} /></button
```suggestion
      uk-tooltip><Fa icon={faAnchor} /></button
```
Can we keep the old anchor icon for this, and use this new icon for the "autofit mode" button?

2024-08-14 22:15 UTC, melange396 commented on src/components/TopMenu.svelte
> +      uk-tooltip><Fa icon={faShuffle} /></button
This is a great icon for this action!

2024-08-14 22:15 UTC, melange396 commented on src/tour.ts
> +  text: `EpiVis supports four navigation modes. Autofit ensures that all enabled datasets are fully displayed on the chart; while Pan, Crop, and Zoom can be used to manipulate the view.`,
```suggestion
  title: 'Toggle between Navigation Modes',
  text: `EpiVis supports four navigation modes: Autofit (the default) ensures that all enabled datasets are fully displayed within the chart, while Pan, Crop, and Zoom can be used to manipulate the view.`,
```

Also, can we move the 3 mouse panning/cropping/zooming tour steps between the "Main Chart" and "Chart Menu" steps?  That will keep the chart-menu-specific stuff together, which i think is clearer.

2024-08-14 22:15 UTC, melange396 commented on src/tour.ts
> +  text: `This action will change the chart view such that all selected datasets are fully shown. Keyboard Shortcut: f`,
Do we want to remove this button now that we have the proper auto-fit mode?  Having two buttons that produce such similar behavior could be confusing.  Every use case i can think of for hitting this button would be achieved by hitting the auto-fit mode button instead.

If we get rid of this button, can we use its icon for the auto-fit mode button?

2024-08-16 12:12 UTC, rzats commented
@melange396 updated!

2024-08-22 17:34 UTC, melange396 approved these changes

2024-08-22 17:35 UTC, merged

2024-08-23 13:51 UTC, melange396 commented
@rzats sorry i missed this before, but we should take out this redundant "f" key (***F***it) action thats been replaced by the "a" key (***A***utofit) action introduced in this pr: https://github.com/cmu-delphi/www-epivis/pull/54/files#diff-15c9be2e78f911b6044c296ac349b7b39aa91dc78f2c499b918f570c0990a164R52-R56